# Generated by Django 4.2.2 on 2023-06-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('createdmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credit_suisse.createdmixin')),
                ('contract_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('credit_suisse.createdmixin',),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('createdmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credit_suisse.createdmixin')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('credit_suisse.createdmixin',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('createdmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credit_suisse.createdmixin')),
                ('name', models.CharField(max_length=100)),
                ('product_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='credit_suisse.producer')),
            ],
            bases=('credit_suisse.createdmixin',),
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('createdmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credit_suisse.createdmixin')),
                ('loan_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='credit_suisse.contract')),
                ('loan_product', models.ManyToManyField(related_name='loan', to='credit_suisse.product')),
            ],
            bases=('credit_suisse.createdmixin',),
        ),
    ]
